spring.application.name=tecabel-interview
spring.datasource.url=jdbc:mysql://localhost:3306/bd_aqui?serverTimezone=UTC
spring.datasource.username=conexion
spring.datasource.password=Conexion123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
